### ISSUE TITLE
'_NamespacePath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by jdknight** [tonybaloney/sphinxcontrib-confluencebuilder#45]
The automated build does not work. The py35 build fails with the following (ex. job [267816857](https://travis-ci.org/tonybaloney/sphinxcontrib-confluencebuilder/jobs/267816857)):

```
Traceback (most recent call last):
  File "/home/travis/build/tonybaloney/sphinxcontrib-confluencebuilder/.tox/py35/bin/pip", line 7, in <module>
    from pip import main
  File "/home/travis/build/tonybaloney/sphinxcontrib-confluencebuilder/.tox/py35/lib/python3.5/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/travis/build/tonybaloney/sphinxcontrib-confluencebuilder/.tox/py35/lib/python3.5/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/home/travis/build/tonybaloney/sphinxcontrib-confluencebuilder/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/home/travis/build/tonybaloney/sphinxcontrib-confluencebuilder/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/home/travis/build/tonybaloney/sphinxcontrib-confluencebuilder/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/home/travis/build/tonybaloney/sphinxcontrib-confluencebuilder/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/home/travis/build/tonybaloney/sphinxcontrib-confluencebuilder/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/travis/build/tonybaloney/sphinxcontrib-confluencebuilder/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/travis/build/tonybaloney/sphinxcontrib-confluencebuilder/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```
I suspect that this problem is not really with the current source of this extension, but rather an issue with `pip` and/or the tox configuration being used.  Using a more recent version pip and setuptools shows that the tox build works; however, I can't seem to get it to work with Travis CI (I haven't had that much experience with using it).

I believe the following bug covers of the reason why, but I'm not 100% sure how to apply the workaround changes for the current automated build process:

> pypa/pip - '_NamespacePath' object has no attribute 'sort'
> pypa/pip#4216

I was hoping a pip v9.0.2 update would fix this, but I'm not sure when an update will ever be released.

**Comment by jdknight** [comment]
This issue has been addressed on `master` to allow Travis CI to be functional again.

For user's experiencing the same issue in their environment, it is recommended to update their `setuptools` package (`python -m pip install --upgrade setuptools`).

**Comment by YB-Park** [comment]
/home/travis/build/tonybaloney/sphinxcontrib-confluencebuilder/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py"

fix line 2121 as shown below.
**`orig_path = sorted(orig_path, key=position_in_sys_path)`**

**Comment by WenkaiChen** [comment]
@YB-Park Thanks a lot, your solution really works for me!

**Comment by FaJoBenWhales** [comment]
YB-Park
the same thing workd for me too 
Thanks a lot, you made my day 
Jochen

**Comment by cestas** [comment]
Thank you YB_Park, that helped me so much. I have no idea though why that issue came up today, even though yesterday it worked just fine!

**Comment by drsxr** [comment]
Thanks YB_Park.  That line fix really should be incorportated into the master build.

**Comment by trantuanvu1602** [comment]
Thanks YB_Park. You made my day!
