### ISSUE TITLE
Incorrect Confluence API base URL and bug handling ConfluenceBadAPI Error

### ISSUE THREAD

**Issue by layoaster** [tonybaloney/sphinxcontrib-confluencebuilder#76]
I was just trying to generate and publish my documentation when I got the following error:

```
Traceback (most recent call last):
  File "/home/layo/projects/venv/onbi-data/lib/python3.6/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/layo/projects/venv/onbi-data/lib/python3.6/site-packages/sphinx/application.py", line 234, in __init__
    self._init_builder()
  File "/home/layo/projects/venv/onbi-data/lib/python3.6/site-packages/sphinx/application.py", line 311, in _init_builder
    self.builder.init()
  File "/home/layo/projects/venv/onbi-data/lib/python3.6/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 98, in init
    self.publisher.connect()
  File "/home/layo/projects/venv/onbi-data/lib/python3.6/site-packages/sphinxcontrib/confluencebuilder/publisher.py", line 67, in connect
    'limit': 1
  File "/home/layo/projects/venv/onbi-data/lib/python3.6/site-packages/sphinxcontrib/confluencebuilder/rest.py", line 52, in get
    raise ConfluenceBadApiError(self._format_error(rsp, key))
  File "/home/layo/projects/venv/onbi-data/lib/python3.6/site-packages/sphinxcontrib/confluencebuilder/rest.py", line 138, in _format_error
    err += "MSG: " + rsp.json()['message']
  File "/home/layo/projects/venv/onbi-data/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I didn't debug the `JSONDecodeError` error but I tried to find why a `ConfluenceBadApiError` was being raised. I found out that the request was returning a 404 and seems that the library was trying to make a request to an invalid API endpoint. I could fix this issue by setting `Rest.BIND_PATH="/wiki/rest/api/"`.

This is my config:
```
confluence_publish = True
confluence_space_name = 'BI'
confluence_parent_page = 'ONBI Sphinx Documentation'
confluence_page_hierarchy = True
confluence_server_url = 'https://-----.atlassian.net'
confluence_server_user = '-----'
confluence_server_pass = '-----'
```
And libs info:

```
# Sphinx version: 1.6.5
# Python version: 3.6.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.9.6
```
I'm not sure if this behaviour is a config issue or a bug. Could you confirm?

**Comment by jdknight** [comment]
It appears to be a configuration issue. Have you tried using the following instead:
```
confluence_server_url = 'https://-----.atlassian.net/wiki'
```
This also appears to be a usability issue -- this isn't the first time (and probably not the last) that people have reported issues trying to properly configure `confluence_server_url`. The [documentation](http://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-server-url) should be update with example cases which cover both Confluence Cloud and Server installations. The server URL was designed to just be the value that would prefix `/rest/api` or `/rpc/xmlrpc`. The parsing of the URL could also be more flexible by also handling a URL that:
- Ends in a forward-slash.
- Has the REST API endpoint set.
- Has the XML-RPC API endpoint set.

Please let me know if the configuration change works for you.

**Comment by layoaster** [comment]
It worked perfectly! As you pointed out this seems to be a documentation issue because the example case and/or the config parameter wording is not self-explanatory enough.

Lastly, it's worth to notice that the `JSONDecodeError` points to a bug when handling the `ConfluenceBadApiError`. Fixing that could also help when dealing with an invalid config of the `confluence_server_url` parameter.

Thanks!

**Comment by jdknight** [comment]
- See #83 for documentation improvements (although, additional tweaks will probably be done if #86 is merged in).
- See #85 for `JSONDecodeError` correction.
- See #86 for flexible Confluence server URL support.

Pending review process before closure.
